# WARNING - Generated by {fusen} from dev/flat_clean_and_merge_indoor.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_and_merge_indoor works", {
  expect_true(inherits(clean_and_merge_indoor, "function"))
})
