# WARNING - Generated by {fusen} from dev/flat_clean_and_merge.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_and_merge works", {
  expect_true(inherits(clean_and_merge, "function"))
})
