# WARNING - Generated by {fusen} from dev/flat_build_local_pipeline.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("build_local_pipeline works", {
  expect_true(inherits(build_local_pipeline, "function"))
})
