# WARNING - Generated by {fusen} from dev/flat_fetch_updated_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fetch_updated_data works", {
  expect_true(inherits(fetch_updated_data, "function"))
})
