# WARNING - Generated by {fusen} from dev/flat_fetch_updated_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("dump_to_disk works", {
  expect_true(inherits(dump_to_disk, "function")) 
})
