# WARNING - Generated by {fusen} from dev/flat_clean_and_merge.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean_and_merge Title
#'
#' @importFrom readr read_csv
#' @importFrom janitor clean_names
#' @importFrom dplyr rename
#' @importFrom purrr map_dfr
#' @return tibble
#' @export
#'
clean_and_merge <- function(raw_data_files) {

  raw_data_files %>%
    map_dfr(~ read_csv(.x) %>%
              clean_names() %>%
              rename(local_date = simple_date)
          )
}
