# WARNING - Generated by {fusen} from dev/flat_clean_and_merge_indoor.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean_and_merge_indoor Title
#'
#' @importFrom readxl read_xlsx
#' @importFrom janitor clean_names
#' @importFrom dplyr rename select mutate full_join arrange
#' @importFrom tidyr fill
#' @importFrom purrr map_dfr
#' @importFrom lubridate with_tz
#' @return tibble
#' @export
#'
clean_and_merge_indoor <- function(raw_data_file, sh_name = "Data", eat = "Indian/Antananarivo") {

  data <- raw_data_file %>%
    read_xlsx(sheet = sh_name) %>%
    clean_names() %>%
    select(-1) %>%
    rename(local_date = date_time_eat) %>%
    mutate(local_date = with_tz(local_date, tzone = eat),
          gmt_date = with_tz(local_date, tzone = "GMT")) %>%
    rename(rel_humidity_percent = rh_percent)
  
  logger_events <- raw_data_file %>%
    read_xlsx(sheet = "Events") %>%
    clean_names() %>%
    rename(local_date = date_time_eat, logging_period = number) %>%
    mutate(local_date = with_tz(local_date, tzone = eat))

  #expand the events to match the full date range of data

  data_clean <- logger_events %>%
    full_join(data) %>%
    arrange(local_date) %>%
    fill(logging_period, .direction = "down")

  data_clean
}
