# WARNING - Generated by {fusen} from dev/flat_fetch_updated_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' Dump Ambient Weather Data to Partitioned Parquet Files
#'
#' Partitions a data frame by date and device, creates a year/month/day folder
#' hierarchy under `output_path`, and writes one parquet file per
#' `year/month/day/device_id` group. Returns a character vector of all file
#' paths under the output directory.
#'
#' @param df A data frame or tibble containing a datetime column and `device_id`.
#' @param proj_root Character scalar. Project root used to build output paths.
#'   Defaults to `here::here()`.
#' @param output_path Character scalar. Relative path under `proj_root` where
#'   data are written (default: `"data/ambient_processed"`).
#' @param dt_col Bare column name for the datetime column used to derive
#'   `year`, `month`, and `day`. Defaults to `date_time`.
#'
#' @return Character vector of full file paths written under `output_path`.
#'
#' @importFrom dplyr mutate distinct group_by group_walk select
#' @importFrom purrr pwalk
#' @importFrom fs dir_create
#' @importFrom here here
#' @importFrom arrow write_parquet
#' @importFrom glue glue
#' @importFrom fs path
#'
#' @examples
#' \dontrun{
#' dump_to_disk(ambient_df, dt_col = date_time)
#' }
#'
#' @export
dump_to_disk <- function(
  df,
  proj_root = here::here(),
  output_path = "data/ambient_processed",
  dt_col = date_time
) {

  df <- df %>%
    mutate(
      dt = as.Date({{dt_col}}),
      year  = format(dt, "%Y"),
      month = format(dt, "%m"),
      day   = format(dt, "%d")
    )

  df %>%
    distinct(year, month, day) %>%
    pwalk(function(year, month, day) {
      dir_create(path(proj_root, output_path, year, month, day))
    })

  df %>%
    group_by(year, month, day, device_id) %>%
    group_walk(function(.x, .y) {

      .x %>%
        select(-dt) %>%
        write_parquet(
          .,
          path(proj_root, output_path, .y$year, .y$month, .y$day, glue("{.y$device_id}_ambient_data_{.y$year}{.y$month}{.y$day}.parquet"))
        )
    })

  return(list.files(path(proj_root, output_path), recursive = TRUE, full.names = TRUE))
}
