# WARNING - Generated by {fusen} from dev/flat_fetch_updated_data.Rmd: do not edit by hand # nolint: line_length_linter.


#' Fetch Updated Ambient Weather Data
#'
#' Fetches device data from Ambient Weather for a date range. If `lookback` is
#' positive, data are fetched from `today - lookback` through today. Otherwise,
#' the function looks for the most recent date in `existing_db_path` and fetches
#' from that day forward (overwriting that day if it already exists).
#'
#' @param device_id Character scalar. Ambient Weather device ID.
#' @param lookback Numeric scalar. Number of days to look back from today.
#'   Use a positive value to fetch recent data; the default `-1` triggers
#'   fetching from the most recent date found in `existing_db_path`.
#' @param existing_db_path Character scalar. Path to existing parquet data
#'   (default: `here::here("data/ambient_processed")`).
#' @param api_key Character scalar. Ambient Weather API key. Defaults to
#'   `Sys.getenv("AMBIENT_WEATHER_API_KEY")`.
#'
#' @return A tibble with device data, sorted by `date_time`, with `device_id`
#'   appended as a column.
#'
#' @importFrom ambientweatheR fetch_device_data
#' @importFrom purrr pluck map_chr map_df
#' @importFrom dplyr as_tibble mutate arrange
#' @importFrom cli cli_alert_info cli_alert_danger cli_alert_success
#' @importFrom here here
#' @importFrom fs dir_exists
#' @importFrom arrow read_parquet
#'
#' @examples
#' \dontrun{
#' fetch_updated_data("C4:D8:D5:3B:4C:F9", lookback = 7)
#' }
#'
#' @export
fetch_updated_data <- function(api_key = Sys.getenv("AMBIENT_WEATHER_API_KEY"), device_id, lookback = -1, existing_db_path = here::here("data/ambient_processed")) {

  today <- Sys.Date()
  if (lookback > 1){
    # in this case, we want to fetch data starting from n days ago until today
    cli_alert_info("Fetching data from the last {lookback} days...")
    start_date <- as.POSIXct(today - lookback)
  
  } else {
    # in this case, we want to check the database for the most recent date we have data
    # for, and start fetching from there
    
    cli_alert_info("Checking most recent date in the database...")
    start_date <- as.POSIXct(today)
    
    if (dir_exists(existing_db_path)) {
      existing_data <- list.files(existing_db_path, recursive = TRUE, full.names = TRUE, pattern = "\\.parquet$") %>%
        map_dfr(read_parquet)
      
      if (nrow(existing_data) > 0) {
        most_recent_date <- max(existing_data$date_time)
        # floor to that day, so it automatically overwrites that day and fetches all data from that day onward
        start_date <- as.Date(most_recent_date)
        cli_alert_info("Most recent date in the database is {most_recent_date}. Fetching data starting from {start_date}...")
      } else {
        cli_alert_danger("No existing data found in the database.")
        stop("No existing data found in the database. Please provide a valid path to the existing database or set lookback to a positive number.")
      }
    } else {
      cli_alert_danger("No existing database found.")
      stop("No existing database found. Please provide a valid path to the existing database or set lookback to a positive number.")
    }
  }

  cli_alert_info("Fetching data starting from {start_date}...")
  seq.Date(from = as.Date(start_date), to = Sys.Date(), by = "days") %>%
    map_chr(as.character) %>%
    map_df(
      ~ fetch_device_data(device_id, .x) %>% 
        pluck("content") %>% 
        as_tibble()
      ) %>%
    mutate(device_id = device_id) %>%
    arrange(date_time) -> output_df
  
  cli_alert_success("Data fetching complete for device {device_id}. Retrieved {nrow(output_df)} records.")
  return(output_df)
}
